# Generated by Django 4.2.20 on 2025-04-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_category_ebook_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='sample_images',
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ebooks/samples/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_images', to='ebooks.ebook')),
            ],
        ),
    ]
