# Generated by Django 5.2 on 2025-04-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_remove_ebook_sample_images_sampleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='ebooks/category_images/default.png', upload_to='ebooks/category_images/'),
        ),
    ]
