# Generated by Django 5.2 on 2025-04-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_subscribed_customuser_subscription_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_start',
        ),
    ]
